[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'